version: "3.5"
networks:
  asa-bridge:
    name: asa-bridge
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=banco
    ports:
      - "5000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      asa-bridge:
        ipv4_address: 172.18.0.20

  projeto_universidade:
    build: .
    ports:
      - "8000:8000"
    networks:
      asa-bridge:
        ipv4_address: 172.18.0.10